### ISSUE TITLE
debug information

### ISSUE THREAD

**Issue by HarelAshwal** [ravikp7/BeagleBoot#10]
LK"I

Hi,
I tried this amazing tool and it stuck at "spi transfer complete"
Is there any way to printout some debug information so I can figure out why is it stuck?

Harel

**Comment by ravikp7** [comment]
Hi Harel, the first step of this app is to boot the board into usb mass storage mode. For that purpose it uses [this bootloader server](https://github.com/ravikp7/node-beagle-boot) . You can try using it. If that works, this app should also work. For further debug info un-comment [this line](https://github.com/ravikp7/node-beagle-boot/blob/19fc0bc9ccfbe1f4f4ea19a98472fae1fc75ee8c/main.js#L47) in bootloader server code and then try.
Also please let me know on which OS you are using the app.
