### ISSUE TITLE
Transfer rate speedup

### ISSUE THREAD

**Issue by BobHeinemann** [ravikp7/BeagleBoot#9]
Hi Ravi

Awesome work.  I am just getting started using it.  The transfer rates seem a little slow for USB.  I'm averaging about 1.5 to 1.6 MB/s.  Do you know why that rate is slow.  Or a better question, where the bottleneck is?

**Comment by ravikp7** [comment]
Hi Bob
Thanks! I've used [etcher-image-write](https://github.com/resin-io-modules/etcher-image-write) module for writing images to the device. So, the bottleneck is due to this module. We need someone to improve it there or find (or write) any alternatives :)
